---
title: "ggplots2"
author: "leon"
date: "29 1 2021"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(here)
```

```{r}
ca_np <- read_csv(here("data", "ca_np.csv"))
```
```{r}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r}
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
```

```{r}
gg_base +
  geom_point(aes(
    size = visitors,
    color = visitors),
    alpha = 0.8,

  )
```

```{r data}
gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  ) +
  theme_linedraw()
```

```{r}
gg_base +
  geom_line(linetype = "dotted") +
    labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )
```

```{r}
gg_base +
  geom_line(color = "purple") +
  geom_point(color = "orange",
             aes(size = year),
             alpha = 0.5)
```

```{r}
gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))
```


```{r}
gg_np +
  geom_line(
    aes(color = park_name)
  )
```
