---
title: "pivot_lobsters"
author: "leon"
date: "31 1 2021"
output: html_document
---

```{r}
## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages('skimr')
library(kableExtra) #install.packages('kableExtra')
```
```{r}
## read in data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
```

```{r}
# explore data
skimr::skim(lobsters) 
```
```{r}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site_and_year = n(),
            mean_size = mean(size_mm, na.rm = TRUE),
            sd_size = sd(size_mm, na.rm = TRUE))

siteyear_summary
```
```{r}
## make a table with our new variable
siteyear_summary %>%
  kable()
```

There are `r nrow(lobsters)` total lobsters included in this report.`

```{r}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE), 
            median_size_mm = median(size_mm, na.rm = TRUE))
siteyear_summary


```
```{r}
ggplot(data = siteyear_summary, aes(x=year, y=median_size_mm,group=site, color=site)) +
       geom_line()
```
```{r}
ggsave(here("figures", "lobster_line.png"))
```

