---
title: "Tidying"
author: "leon"
date: "1 2 2021"
output: html_document
---

```{r}
inverts <- read_excel(here("data", "inverts.xlsx"))
```

```{r}
inverts_long <- pivot_longer(data = inverts,
                             cols = "2016":"2018",
                             names_to = "year",
                             values_to = "sp_count")
inverts_long
  
```
```{r}
inverts_long <- inverts_long %>%
  mutate(year = as.numeric(year))
inverts_long
```
```{r}
inverts_wide <- inverts_long %>% 
  pivot_wider(names_from = common_name, 
                     values_from = sp_count)
inverts_wide
```
```{r}
inverts_wide <- inverts_wide %>% 
  clean_names()
inverts_wide
```
```{r}
inverts_unite <- inverts_long %>% 
  unite(col = "site_year", # What to name the new united column
               c(site, year), # The columns we'll unite (site, year)
               sep = "_") # How to separate the things we're uniting
inverts_unite
```

```{r}
inverts_month_year <- inverts_long %>%
  unite(month_year,
        c(month, year),
        sep = "/")
inverts_month_year
```
```{r}
inverts_sep <- inverts_unite %>% 
  tidyr::separate(site_year, into = c("my_site", "my_year"))
inverts_sep
```
```{r}
ca_abbr <- inverts %>% 
  mutate(
    common_name = 
      str_replace(common_name, 
              pattern = "california", 
              replacement = "CA")
  )
ca_abbr
```

